apiVersion: v1
kind: Service
metadata:
  name: bermtecuserservice
  namespace: bermtecpayment
spec:
  selector:
    app: bermtecuser-dev
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: http-port
    protocol: TCP
    port: 80
    targetPort: 8080